version: 2.1

orbs:
  go: circleci/go@1.11.0

jobs:
  test:
    executor:
      name: go/default
      tag: '1.22.4'
    steps:
      - checkout
      - restore_cache:
          name: Restore Go caches
          keys:
            - go-dependencies-{{ checksum "go.sum" }}
      - run:
          name: Go mod download
          command: go mod download
      - run:
          name: Go test
          command: go test . -v
      - save_cache:
          name: Save Go caches
          key: go-dependencies-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod # GOMODCACHE (module cache)
            - /home/circleci/.cache/go-build # GOCACHE (build cache)

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  example:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
      # - build:
      #     requires:
      #       - test
      # - deploy:
      #     requires:
      #       - test
