name: API Test
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  check-files:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all branches
      - id: changed-files
        uses: tj-actions/changed-files@v18.5 # https://github.com/tj-actions/changed-files
      - run: |
          echo 'Changed files: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}'
    outputs:
      testTarget: ${{ contains(steps.changed-files.outputs.all_changed_and_modified_files, 'target/') }}
    
  test:
    runs-on: ubuntu-latest
    needs: check-files
    if: needs.check-files.outputs.testTarget
    steps:
      - id: start-check
        uses: LouisBrunner/checks-action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test
          status: queued
      - name: Start pipeline
        run: |-
          curl -X POST -H "Content-Type: application/json" -d '{
            "ref": "${{ github.head_ref }}",
            "checkId": "${{ steps.start-check.outputs.check_id }}",
            "testTarget": ${{ needs.check-files.outputs.testTarget }}
          }' ${CIRCLECI_WEBHOOK}
        env:
          CIRCLECI_WEBHOOK: ${{ secrets.CIRCLECI_WEBHOOK }}
