name: API Test
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'target/**'
      - '.github/workflows/test.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: WebHook
          run: |
            curl -X POST -H "Content-Type: application/json" -d '{"ref":"${{ github.head_ref }}"}' ${CIRCLECI_WEBHOOK}
          env:
            CIRCLECI_WEBHOOK: ${{ secrets.CIRCLECI_WEBHOOK }}
