name: API Test
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'target/**'
      - '.github/workflows/test.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: WebHook
          run: curl ${CIRCLECI_WEBHOOK}
          env:
            CIRCLECI_WEBHOOK: ${{ CIRCLECI_WEBHOOK }}
